### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/wg-bento#59]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by dvoytenko** [comment]
LGTM

**Comment by rsimha** [comment]
Done. Screenshot for posterity:

![image](https://user-images.githubusercontent.com/26553114/113944321-57638b80-97d2-11eb-93d4-72ea39e49b7e.png)
